### PR TITLE
Improve documentation in README.md file

### PR DESCRIPTION
**Pull request by kizule**
This tool can list contributions from other wikis, no just Wikipedia.

### CODE REVIEW

**Comment by kizule** [comment]
Maybe an option for exporting should be added in the documentation too.

**Comment by kizule** [comment]
> Maybe an option for exporting should be added in the documentation too.

What you think @Dineshkarthik?

**Comment by Dineshkarthik** [comment]
Exporting is explicit via button, maybe we can add it as well,

**Comment by kizule** [comment]
> Exporting is explicit via button, maybe we can add it as well,

Done in #8.

**Pull request merged**
